- name: set variable
  set_fact:
    consul_token: "{{ lookup('env', 'consul_master_token') }}"

- name: Check if intention count-dashboard => count-api (allow) exists
  shell: consul intention match -source count-dashboard
  register: count_dashboard_intention
  when: lookup('env', 'consul_acl') | bool and lookup('env', 'consul_acl_default_policy') == 'deny'
  environment:
    CONSUL_HTTP_TOKEN: "{{ consul_token }}"

- name: Consul create intention count-dashboard => count-api (allow)
  shell: consul intention create count-dashboard count-api
  when: lookup('env', 'consul_acl') | bool and lookup('env', 'consul_acl_default_policy') == 'deny' and count_dashboard_intention.stdout_lines == []
  environment:
    CONSUL_HTTP_TOKEN: "{{ consul_token }}"
